[package]
name = "access_control"
version = "0.2.0"
cairo-version = "2.4.0"
authors = ["Lindy Labs"]
description = "Member-based access control component for Cairo"
readme = "README.md"
repository = "https://github.com/lindy-labs/access_control"
license-file = "LICENSE"
keywords = ["access control", "authorization", "cairo", "starknet"]

[dependencies]
starknet = "2.4.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }

[lib]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[scripts]
test = "snforge test"